### ISSUE TITLE
As a customer, I want a FAQ page so that I can find more information regarding the app and the store.

### ISSUE THREAD

**Issue by bijoy-shah** [HamishAitken/AgileCourseworkGroup3#14]
### Acceptance Criteria
- [ ] Create a page with basic information about the app
- [ ] Create a link to the About Us of the stores website

### Definition of Done
- [ ] All code works as intended 
- [ ] All pages/features are fully accessible 
- [ ] All pages/features are fully responsive
- [ ] All code is well commented
- [ ] All code is reviewed
- [ ] All code is integrated

**Comment by ndomvi** [comment]
LGL said that they want the FAQ link to lead to their store website.
